---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image-ecr
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test-ecr
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./build
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 205429787317.dkr.ecr.ap-south-1.amazonaws.com
              docker pull 205429787317.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest
              docker stop my_container || true
              docker rm my_container || true
              docker run --name my_container-p 3000:3000 -d 205429787317.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest
